name: ChatColorHandlerTest
version: '${version}'
main: org.lushplugins.chatcolorhandlertest.spigot.ChatColorHandlerTest
api-version: '1.17'
softdepend:
  - PlaceholderAPI
  - MiniPlaceholders
commands:
  chatcolorhandlertest:
    description: ChatColorHandlerTest Command
    usage: /chatcolorhandlertest